{% set version = "1.0.0" %}

package:
  name: locket
  version: {{ version }}

source:
  fn: locket-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/l/locket/locket-{{ version }}.tar.gz
  md5: fff6d2fcd92fbeb9af9dbc260eb0b5e8

build:
  noarch: python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*

test:
  imports:
    - locket

about:
  home: https://github.com/mwilliamson/locket.py
  license: BSD-2-Clause
  license_file: LICENSE
  summary: File-based locks for Python for Linux and Windows

extra:
  recipe-maintainers:
    - jcrist
